import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/#/login');
  await page.getByRole('textbox', { name: 'Correo electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).fill('supervisor.mobile@arquitech.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Arquitech123!');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByText('E2E Proyecto Playwright', { exact: true }).waitFor();
  await page.getByText('E2E Proyecto Playwright', { exact: true }).click();
  await page.getByText('Personal', { exact: true }).click();
  await page.getByRole('button', { name: 'Crear', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nombre completo', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nombre completo', exact: true }).fill('Trabajador E2E Playwright');
  await page.getByRole('button', { name: /Cargo/ }).click();
  await page.getByRole('menuitem', { name: 'Albañil', exact: true }).click();
  await page.getByRole('textbox', { name: 'Especialidad', exact: true }).click();
  await page.getByRole('textbox', { name: 'Especialidad', exact: true }).fill('Acabados E2E Playwright');
  await page.getByRole('textbox', { name: 'Fecha de contratación', exact: true }).click();
  await page.getByRole('textbox', { name: 'Fecha de contratación', exact: true }).fill('2026-01-01');
  await page.getByRole('button', { name: 'Guardar', exact: true }).click();
  await page.getByRole('button', { name: 'Personal', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Asistencia', exact: true }).click();
  await page.getByRole('button', { name: 'Crear', exact: true }).click();
  await page.getByRole('button', { name: /Trabajador/ }).click();
  await page.getByRole('menuitem', { name: 'Trabajador E2E Playwright', exact: true }).click();
  await page.getByRole('button', { name: /Estado/ }).click();
  await page.getByRole('menuitem', { name: 'Presente', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nota', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nota', exact: true }).fill('Asistencia E2E Playwright');
  await page.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page).toHaveURL(/#\/projects\/\d+\/attendance$/);
  await expect(page.getByRole('region', { name: 'Asistencia', exact: true }).getByText('Trabajador E2E Playwright', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Asistencia', exact: true }).getByText('Presente', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Asistencia', exact: true }).getByText('Asistencia E2E Playwright', { exact: true })).toBeVisible();
});
