import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/#/login');
  await page.getByRole('textbox', { name: 'Correo electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).fill('supervisor.mobile@arquitech.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Arquitech123!');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByText('E2E Proyecto Playwright', { exact: true }).waitFor();
  await page.getByText('E2E Proyecto Playwright', { exact: true }).click();
  await page.getByRole('button', { name: 'Nuevo material', exact: true }).click();
  await page.getByRole('textbox', { name: 'Material', exact: true }).click();
  await page.getByRole('textbox', { name: 'Material', exact: true }).fill('Cemento E2E Playwright');
  await page.getByRole('textbox', { name: 'Unidad', exact: true }).click();
  await page.getByRole('textbox', { name: 'Unidad', exact: true }).fill('bolsa');
  await page.getByRole('textbox', { name: 'Cantidad recibida', exact: true }).click();
  await page.getByRole('textbox', { name: 'Cantidad recibida', exact: true }).fill('20');
  await page.getByRole('textbox', { name: 'Stock mínimo', exact: true }).click();
  await page.getByRole('textbox', { name: 'Stock mínimo', exact: true }).fill('5');
  await page.getByRole('textbox', { name: 'Precio unitario', exact: true }).click();
  await page.getByRole('textbox', { name: 'Precio unitario', exact: true }).fill('30.50');
  await page.getByRole('textbox', { name: 'Proveedor', exact: true }).click();
  await page.getByRole('textbox', { name: 'Proveedor', exact: true }).fill('Proveedor E2E Playwright');
  await page.getByRole('textbox', { name: 'RUC del proveedor', exact: true }).click();
  await page.getByRole('textbox', { name: 'RUC del proveedor', exact: true }).fill('20123456789');
  await page.getByRole('button', { name: 'Guardar', exact: true }).click();
  await page.getByRole('button', { name: 'Material: Cemento E2E Playwright', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Registrar entrada', exact: true }).click();
  await page.getByRole('textbox', { name: /^Cantidad recibida/ }).click();
  await page.getByRole('textbox', { name: /^Cantidad recibida/ }).fill('10');
  await page.getByRole('textbox', { name: 'Proveedor de la entrada', exact: true }).click();
  await page.getByRole('textbox', { name: 'Proveedor de la entrada', exact: true }).fill('Proveedor E2E Playwright');
  await page.getByRole('textbox', { name: /^Nota \(Opcional\)/ }).click();
  await page.getByRole('textbox', { name: /^Nota \(Opcional\)/ }).fill('Entrada E2E Playwright de 10 bolsas');
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click();
  await page.getByRole('region', { name: 'Cemento E2E Playwright', exact: true }).getByRole('region', { name: 'Stock disponible', exact: true }).getByText('30 bolsa', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Material: Cemento E2E Playwright', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Registrar uso', exact: true }).click();
  await page.getByRole('textbox', { name: /^Cantidad recibida/ }).click();
  await page.getByRole('textbox', { name: /^Cantidad recibida/ }).fill('5');
  await page.getByRole('textbox', { name: /^Nota \(Opcional\)/ }).click();
  await page.getByRole('textbox', { name: /^Nota \(Opcional\)/ }).fill('Uso E2E Playwright de 5 bolsas');
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click();
  await page.getByRole('region', { name: 'Cemento E2E Playwright', exact: true }).getByRole('region', { name: 'Stock disponible', exact: true }).getByText('25 bolsa', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Historial', exact: true }).click();
  await expect(page).toHaveURL(/#\/projects\/\d+\/materials\/history$/);
  await expect(page.getByText('Entrada E2E Playwright de 10 bolsas', { exact: true })).toBeVisible();
  await expect(page.getByText('Uso E2E Playwright de 5 bolsas', { exact: true })).toBeVisible();
  await expect(page.getByText(/^\+10(?:\.0)? bolsa$/)).toBeVisible();
  await expect(page.getByText(/^-5(?:\.0)? bolsa$/)).toBeVisible();
});
