import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/#/login');
  await page.getByRole('textbox', { name: 'Correo electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).fill('contratista.mobile@arquitech.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Arquitech123!');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByText('E2E Proyecto Playwright', { exact: true }).waitFor();
  await expect(page).toHaveURL(/#\/projects$/);
  await expect(page.getByRole('button', { name: 'Nuevo proyecto', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Eliminar proyecto', exact: true })).toHaveCount(0);
  await page.getByText('E2E Proyecto Playwright', { exact: true }).click();
  await expect(page.getByRole('region', { name: 'Cemento E2E Playwright', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Nuevo material', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Material: Cemento E2E Playwright', exact: true })).toHaveCount(0);
  await page.getByText('Personal', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar', exact: true }).fill('Trabajador E2E Playwright');
  await expect(page.getByRole('region', { name: 'Trabajadores', exact: true }).getByText('Trabajador E2E Playwright', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Crear', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Editar', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Eliminar', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Asignar tarea', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Personal', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Tareas', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar', exact: true }).fill('Tarea E2E Playwright');
  await expect(page.getByRole('region', { name: 'Tareas', exact: true }).getByText('Tarea E2E Playwright', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Crear', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Completar', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Editar', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Eliminar', exact: true })).toHaveCount(0);
  await page.getByText('Más', { exact: true }).click();
  await page.getByText('Reportes', { exact: true }).click();
  await expect(page.getByRole('region', { name: 'Tareas completadas', exact: true }).getByText('Tarea E2E Playwright', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Generar PDF', exact: true })).toHaveCount(0);
  await page.getByText('Más', { exact: true }).click();
  await page.getByText('Cerrar sesión', { exact: true }).click();
  await expect(page).toHaveURL(/#\/login$/);
  await expect(page.getByRole('textbox', { name: 'Correo electrónico' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ingresar', exact: true })).toBeVisible();
});
